spec-version: 0.30.0
name: hiedb-plugin
author: Joseph Sumabat
synopsis: See README on Github for more information 
description: Automatically index in hiedb on recompiliation
category: Development
maintainer: josephrsumabat@gmail.com
github: josephsumabat/hiedb-plugin
license: MIT
version: 0.1.0
build-type: Simple
extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.17.0 && < 4.20
  - directory >= 1.3.7 && < 1.4
  - filepath >= 1.4.1 && < 1.5
  - ghc >= 9.6.0 && < 9.10
  - hiedb >= 0.6.0.0 && < 0.7.0.0
  - stm >= 2.5.1.0 && < 2.6.0.0

default-extensions:
- FlexibleContexts
- LambdaCase
- NoFieldSelectors
- OverloadedRecordDot
- OverloadedStrings
- ScopedTypeVariables

ghc-options:
  - -Wall

library:
  source-dirs: src
  ghc-options:
  - -fwrite-ide-info
